// Generated by gencpp from file roadbot_control/ac_go_signstand_Args.msg
// DO NOT EDIT!


#ifndef ROADBOT_CONTROL_MESSAGE_AC_GO_SIGNSTAND_ARGS_H
#define ROADBOT_CONTROL_MESSAGE_AC_GO_SIGNSTAND_ARGS_H

#include <ros/service_traits.h>


#include <roadbot_control/ac_go_signstand_ArgsRequest.h>
#include <roadbot_control/ac_go_signstand_ArgsResponse.h>


namespace roadbot_control
{

struct ac_go_signstand_Args
{

typedef ac_go_signstand_ArgsRequest Request;
typedef ac_go_signstand_ArgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ac_go_signstand_Args
} // namespace roadbot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roadbot_control::ac_go_signstand_Args > {
  static const char* value()
  {
    return "caec67dc8933c4357cb62028f1056dfe";
  }

  static const char* value(const ::roadbot_control::ac_go_signstand_Args&) { return value(); }
};

template<>
struct DataType< ::roadbot_control::ac_go_signstand_Args > {
  static const char* value()
  {
    return "roadbot_control/ac_go_signstand_Args";
  }

  static const char* value(const ::roadbot_control::ac_go_signstand_Args&) { return value(); }
};


// service_traits::MD5Sum< ::roadbot_control::ac_go_signstand_ArgsRequest> should match
// service_traits::MD5Sum< ::roadbot_control::ac_go_signstand_Args >
template<>
struct MD5Sum< ::roadbot_control::ac_go_signstand_ArgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roadbot_control::ac_go_signstand_Args >::value();
  }
  static const char* value(const ::roadbot_control::ac_go_signstand_ArgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roadbot_control::ac_go_signstand_ArgsRequest> should match
// service_traits::DataType< ::roadbot_control::ac_go_signstand_Args >
template<>
struct DataType< ::roadbot_control::ac_go_signstand_ArgsRequest>
{
  static const char* value()
  {
    return DataType< ::roadbot_control::ac_go_signstand_Args >::value();
  }
  static const char* value(const ::roadbot_control::ac_go_signstand_ArgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roadbot_control::ac_go_signstand_ArgsResponse> should match
// service_traits::MD5Sum< ::roadbot_control::ac_go_signstand_Args >
template<>
struct MD5Sum< ::roadbot_control::ac_go_signstand_ArgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roadbot_control::ac_go_signstand_Args >::value();
  }
  static const char* value(const ::roadbot_control::ac_go_signstand_ArgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roadbot_control::ac_go_signstand_ArgsResponse> should match
// service_traits::DataType< ::roadbot_control::ac_go_signstand_Args >
template<>
struct DataType< ::roadbot_control::ac_go_signstand_ArgsResponse>
{
  static const char* value()
  {
    return DataType< ::roadbot_control::ac_go_signstand_Args >::value();
  }
  static const char* value(const ::roadbot_control::ac_go_signstand_ArgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROADBOT_CONTROL_MESSAGE_AC_GO_SIGNSTAND_ARGS_H
