// Generated by gencpp from file roadbot_control/ac_go_signstand_ArgsRequest.msg
// DO NOT EDIT!


#ifndef ROADBOT_CONTROL_MESSAGE_AC_GO_SIGNSTAND_ARGSREQUEST_H
#define ROADBOT_CONTROL_MESSAGE_AC_GO_SIGNSTAND_ARGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roadbot_control
{
template <class ContainerAllocator>
struct ac_go_signstand_ArgsRequest_
{
  typedef ac_go_signstand_ArgsRequest_<ContainerAllocator> Type;

  ac_go_signstand_ArgsRequest_()
    : position_y(0.0)
    , position_x(0.0)
    , lb_location(0)  {
    }
  ac_go_signstand_ArgsRequest_(const ContainerAllocator& _alloc)
    : position_y(0.0)
    , position_x(0.0)
    , lb_location(0)  {
  (void)_alloc;
    }



   typedef double _position_y_type;
  _position_y_type position_y;

   typedef double _position_x_type;
  _position_x_type position_x;

   typedef int64_t _lb_location_type;
  _lb_location_type lb_location;





  typedef boost::shared_ptr< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ac_go_signstand_ArgsRequest_

typedef ::roadbot_control::ac_go_signstand_ArgsRequest_<std::allocator<void> > ac_go_signstand_ArgsRequest;

typedef boost::shared_ptr< ::roadbot_control::ac_go_signstand_ArgsRequest > ac_go_signstand_ArgsRequestPtr;
typedef boost::shared_ptr< ::roadbot_control::ac_go_signstand_ArgsRequest const> ac_go_signstand_ArgsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator1> & lhs, const ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.position_y == rhs.position_y &&
    lhs.position_x == rhs.position_x &&
    lhs.lb_location == rhs.lb_location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator1> & lhs, const ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roadbot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "738f20e8f6ccbabd4b9be9a38350a552";
  }

  static const char* value(const ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x738f20e8f6ccbabdULL;
  static const uint64_t static_value2 = 0x4b9be9a38350a552ULL;
};

template<class ContainerAllocator>
struct DataType< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roadbot_control/ac_go_signstand_ArgsRequest";
  }

  static const char* value(const ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 position_y\n"
"float64 position_x\n"
"\n"
"\n"
"int64 lb_location\n"
;
  }

  static const char* value(const ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position_y);
      stream.next(m.position_x);
      stream.next(m.lb_location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ac_go_signstand_ArgsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roadbot_control::ac_go_signstand_ArgsRequest_<ContainerAllocator>& v)
  {
    s << indent << "position_y: ";
    Printer<double>::stream(s, indent + "  ", v.position_y);
    s << indent << "position_x: ";
    Printer<double>::stream(s, indent + "  ", v.position_x);
    s << indent << "lb_location: ";
    Printer<int64_t>::stream(s, indent + "  ", v.lb_location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROADBOT_CONTROL_MESSAGE_AC_GO_SIGNSTAND_ARGSREQUEST_H
