set(_CATKIN_CURRENT_PACKAGE "fslidar_drive")
set(fslidar_drive_VERSION "0.0.0")
set(fslidar_drive_MAINTAINER "kuang <loveredhome@126.com>")
set(fslidar_drive_PACKAGE_FORMAT "1")
set(fslidar_drive_BUILD_DEPENDS "roscpp" "sensor_msgs" "std_msgs")
set(fslidar_drive_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "std_msgs")
set(fslidar_drive_BUILDTOOL_DEPENDS "catkin")
set(fslidar_drive_BUILDTOOL_EXPORT_DEPENDS )
set(fslidar_drive_EXEC_DEPENDS "roscpp" "sensor_msgs" "std_msgs")
set(fslidar_drive_RUN_DEPENDS "roscpp" "sensor_msgs" "std_msgs")
set(fslidar_drive_TEST_DEPENDS )
set(fslidar_drive_DOC_DEPENDS )
set(fslidar_drive_URL_WEBSITE "")
set(fslidar_drive_URL_BUGTRACKER "")
set(fslidar_drive_URL_REPOSITORY "")
set(fslidar_drive_DEPRECATED "")