// Generated by gencpp from file cone_sensor/cs_set_bool_Args.msg
// DO NOT EDIT!


#ifndef CONE_SENSOR_MESSAGE_CS_SET_BOOL_ARGS_H
#define CONE_SENSOR_MESSAGE_CS_SET_BOOL_ARGS_H

#include <ros/service_traits.h>


#include <cone_sensor/cs_set_bool_ArgsRequest.h>
#include <cone_sensor/cs_set_bool_ArgsResponse.h>


namespace cone_sensor
{

struct cs_set_bool_Args
{

typedef cs_set_bool_ArgsRequest Request;
typedef cs_set_bool_ArgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cs_set_bool_Args
} // namespace cone_sensor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cone_sensor::cs_set_bool_Args > {
  static const char* value()
  {
    return "01ed7128038a1bd09607b70544351d27";
  }

  static const char* value(const ::cone_sensor::cs_set_bool_Args&) { return value(); }
};

template<>
struct DataType< ::cone_sensor::cs_set_bool_Args > {
  static const char* value()
  {
    return "cone_sensor/cs_set_bool_Args";
  }

  static const char* value(const ::cone_sensor::cs_set_bool_Args&) { return value(); }
};


// service_traits::MD5Sum< ::cone_sensor::cs_set_bool_ArgsRequest> should match
// service_traits::MD5Sum< ::cone_sensor::cs_set_bool_Args >
template<>
struct MD5Sum< ::cone_sensor::cs_set_bool_ArgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cone_sensor::cs_set_bool_Args >::value();
  }
  static const char* value(const ::cone_sensor::cs_set_bool_ArgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cone_sensor::cs_set_bool_ArgsRequest> should match
// service_traits::DataType< ::cone_sensor::cs_set_bool_Args >
template<>
struct DataType< ::cone_sensor::cs_set_bool_ArgsRequest>
{
  static const char* value()
  {
    return DataType< ::cone_sensor::cs_set_bool_Args >::value();
  }
  static const char* value(const ::cone_sensor::cs_set_bool_ArgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cone_sensor::cs_set_bool_ArgsResponse> should match
// service_traits::MD5Sum< ::cone_sensor::cs_set_bool_Args >
template<>
struct MD5Sum< ::cone_sensor::cs_set_bool_ArgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cone_sensor::cs_set_bool_Args >::value();
  }
  static const char* value(const ::cone_sensor::cs_set_bool_ArgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cone_sensor::cs_set_bool_ArgsResponse> should match
// service_traits::DataType< ::cone_sensor::cs_set_bool_Args >
template<>
struct DataType< ::cone_sensor::cs_set_bool_ArgsResponse>
{
  static const char* value()
  {
    return DataType< ::cone_sensor::cs_set_bool_Args >::value();
  }
  static const char* value(const ::cone_sensor::cs_set_bool_ArgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONE_SENSOR_MESSAGE_CS_SET_BOOL_ARGS_H
