set(_CATKIN_CURRENT_PACKAGE "roadbot_hmi")
set(roadbot_hmi_VERSION "0.0.0")
set(roadbot_hmi_MAINTAINER "ivanyip <ivanyip@todo.todo>")
set(roadbot_hmi_PACKAGE_FORMAT "2")
set(roadbot_hmi_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "kuka_robot")
set(roadbot_hmi_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "kuka_robot")
set(roadbot_hmi_BUILDTOOL_DEPENDS "catkin")
set(roadbot_hmi_BUILDTOOL_EXPORT_DEPENDS )
set(roadbot_hmi_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "kuka_robot")
set(roadbot_hmi_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "kuka_robot")
set(roadbot_hmi_TEST_DEPENDS )
set(roadbot_hmi_DOC_DEPENDS )
set(roadbot_hmi_URL_WEBSITE "")
set(roadbot_hmi_URL_BUGTRACKER "")
set(roadbot_hmi_URL_REPOSITORY "")
set(roadbot_hmi_DEPRECATED "")