// Generated by gencpp from file vision_system/vs_get_white_marking_position_ArgsRequest.msg
// DO NOT EDIT!


#ifndef VISION_SYSTEM_MESSAGE_VS_GET_WHITE_MARKING_POSITION_ARGSREQUEST_H
#define VISION_SYSTEM_MESSAGE_VS_GET_WHITE_MARKING_POSITION_ARGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_system
{
template <class ContainerAllocator>
struct vs_get_white_marking_position_ArgsRequest_
{
  typedef vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> Type;

  vs_get_white_marking_position_ArgsRequest_()
    : timestamp(0.0)
    , x(0.0)
    , y(0.0)  {
    }
  vs_get_white_marking_position_ArgsRequest_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct vs_get_white_marking_position_ArgsRequest_

typedef ::vision_system::vs_get_white_marking_position_ArgsRequest_<std::allocator<void> > vs_get_white_marking_position_ArgsRequest;

typedef boost::shared_ptr< ::vision_system::vs_get_white_marking_position_ArgsRequest > vs_get_white_marking_position_ArgsRequestPtr;
typedef boost::shared_ptr< ::vision_system::vs_get_white_marking_position_ArgsRequest const> vs_get_white_marking_position_ArgsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator1> & lhs, const ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator1> & lhs, const ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c67d7bc3d48d1375ae2843b52c2502d0";
  }

  static const char* value(const ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc67d7bc3d48d1375ULL;
  static const uint64_t static_value2 = 0xae2843b52c2502d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_system/vs_get_white_marking_position_ArgsRequest";
  }

  static const char* value(const ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 timestamp\n"
"\n"
"\n"
"float64 x\n"
"float64 y\n"
"\n"
;
  }

  static const char* value(const ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vs_get_white_marking_position_ArgsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_system::vs_get_white_marking_position_ArgsRequest_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_SYSTEM_MESSAGE_VS_GET_WHITE_MARKING_POSITION_ARGSREQUEST_H
