// Generated by gencpp from file vision_system/vs_send_cali_data_Args.msg
// DO NOT EDIT!


#ifndef VISION_SYSTEM_MESSAGE_VS_SEND_CALI_DATA_ARGS_H
#define VISION_SYSTEM_MESSAGE_VS_SEND_CALI_DATA_ARGS_H

#include <ros/service_traits.h>


#include <vision_system/vs_send_cali_data_ArgsRequest.h>
#include <vision_system/vs_send_cali_data_ArgsResponse.h>


namespace vision_system
{

struct vs_send_cali_data_Args
{

typedef vs_send_cali_data_ArgsRequest Request;
typedef vs_send_cali_data_ArgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct vs_send_cali_data_Args
} // namespace vision_system


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision_system::vs_send_cali_data_Args > {
  static const char* value()
  {
    return "f30152e5d2a43a58c59d2b40816d1dd0";
  }

  static const char* value(const ::vision_system::vs_send_cali_data_Args&) { return value(); }
};

template<>
struct DataType< ::vision_system::vs_send_cali_data_Args > {
  static const char* value()
  {
    return "vision_system/vs_send_cali_data_Args";
  }

  static const char* value(const ::vision_system::vs_send_cali_data_Args&) { return value(); }
};


// service_traits::MD5Sum< ::vision_system::vs_send_cali_data_ArgsRequest> should match
// service_traits::MD5Sum< ::vision_system::vs_send_cali_data_Args >
template<>
struct MD5Sum< ::vision_system::vs_send_cali_data_ArgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision_system::vs_send_cali_data_Args >::value();
  }
  static const char* value(const ::vision_system::vs_send_cali_data_ArgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_system::vs_send_cali_data_ArgsRequest> should match
// service_traits::DataType< ::vision_system::vs_send_cali_data_Args >
template<>
struct DataType< ::vision_system::vs_send_cali_data_ArgsRequest>
{
  static const char* value()
  {
    return DataType< ::vision_system::vs_send_cali_data_Args >::value();
  }
  static const char* value(const ::vision_system::vs_send_cali_data_ArgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision_system::vs_send_cali_data_ArgsResponse> should match
// service_traits::MD5Sum< ::vision_system::vs_send_cali_data_Args >
template<>
struct MD5Sum< ::vision_system::vs_send_cali_data_ArgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision_system::vs_send_cali_data_Args >::value();
  }
  static const char* value(const ::vision_system::vs_send_cali_data_ArgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_system::vs_send_cali_data_ArgsResponse> should match
// service_traits::DataType< ::vision_system::vs_send_cali_data_Args >
template<>
struct DataType< ::vision_system::vs_send_cali_data_ArgsResponse>
{
  static const char* value()
  {
    return DataType< ::vision_system::vs_send_cali_data_Args >::value();
  }
  static const char* value(const ::vision_system::vs_send_cali_data_ArgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_SYSTEM_MESSAGE_VS_SEND_CALI_DATA_ARGS_H
