(cl:in-package lidar_tracker-msg)
(cl:export '(ID-VAL
          ID
          IDTIMESTAMP-VAL
          IDTIMESTAMP
          UPDATEINTERVAL-VAL
          UPDATEINTERVAL
          RATIOM-VAL
          RATIOM
          MINPOINT-VAL
          MINPOINT
          INCEDGE-VAL
          INCEDGE
          DECEDGE-VAL
          DECEDGE
          CENTERPOINT-VAL
          CENTERPOINT
          STABLEREFPOINT-VAL
          STABLEREFPOINT
          SIZE-VAL
          SIZE
          IS_CONE-VAL
          IS_CONE
          IS_TRACKED-VAL
          IS_TRACKED
          EST_VEL-VAL
          EST_VEL
          EST_ACC-VAL
          EST_ACC
          IS_FUSED-VAL
          IS_FUSED
          INCLINE-VAL
          INCLINE
          ROTATE-VAL
          ROTATE
))