; Auto-generated. Do not edit!


(cl:in-package lidar_tracker-msg)


;//! \htmlinclude lt_state_Type.msg.html

(cl:defclass <lt_state_Type> (roslisp-msg-protocol:ros-message)
  ((timestamp
    :reader timestamp
    :initarg :timestamp
    :type cl:float
    :initform 0.0)
   (lidars_difftime
    :reader lidars_difftime
    :initarg :lidars_difftime
    :type cl:float
    :initform 0.0)
   (objects
    :reader objects
    :initarg :objects
    :type (cl:vector lidar_tracker-msg:lt_object_Type)
   :initform (cl:make-array 0 :element-type 'lidar_tracker-msg:lt_object_Type :initial-element (cl:make-instance 'lidar_tracker-msg:lt_object_Type)))
   (trackedcone_indexes
    :reader trackedcone_indexes
    :initarg :trackedcone_indexes
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (noncone_indexes
    :reader noncone_indexes
    :initarg :noncone_indexes
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (num_of_fusedobjects
    :reader num_of_fusedobjects
    :initarg :num_of_fusedobjects
    :type cl:integer
    :initform 0)
   (columnscan_up_dist
    :reader columnscan_up_dist
    :initarg :columnscan_up_dist
    :type (cl:vector cl:float)
   :initform (cl:make-array 8 :element-type 'cl:float :initial-element 0.0))
   (columnscan_down_dist
    :reader columnscan_down_dist
    :initarg :columnscan_down_dist
    :type (cl:vector cl:float)
   :initform (cl:make-array 8 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass lt_state_Type (<lt_state_Type>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <lt_state_Type>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'lt_state_Type)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lidar_tracker-msg:<lt_state_Type> is deprecated: use lidar_tracker-msg:lt_state_Type instead.")))

(cl:ensure-generic-function 'timestamp-val :lambda-list '(m))
(cl:defmethod timestamp-val ((m <lt_state_Type>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lidar_tracker-msg:timestamp-val is deprecated.  Use lidar_tracker-msg:timestamp instead.")
  (timestamp m))

(cl:ensure-generic-function 'lidars_difftime-val :lambda-list '(m))
(cl:defmethod lidars_difftime-val ((m <lt_state_Type>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lidar_tracker-msg:lidars_difftime-val is deprecated.  Use lidar_tracker-msg:lidars_difftime instead.")
  (lidars_difftime m))

(cl:ensure-generic-function 'objects-val :lambda-list '(m))
(cl:defmethod objects-val ((m <lt_state_Type>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lidar_tracker-msg:objects-val is deprecated.  Use lidar_tracker-msg:objects instead.")
  (objects m))

(cl:ensure-generic-function 'trackedcone_indexes-val :lambda-list '(m))
(cl:defmethod trackedcone_indexes-val ((m <lt_state_Type>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lidar_tracker-msg:trackedcone_indexes-val is deprecated.  Use lidar_tracker-msg:trackedcone_indexes instead.")
  (trackedcone_indexes m))

(cl:ensure-generic-function 'noncone_indexes-val :lambda-list '(m))
(cl:defmethod noncone_indexes-val ((m <lt_state_Type>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lidar_tracker-msg:noncone_indexes-val is deprecated.  Use lidar_tracker-msg:noncone_indexes instead.")
  (noncone_indexes m))

(cl:ensure-generic-function 'num_of_fusedobjects-val :lambda-list '(m))
(cl:defmethod num_of_fusedobjects-val ((m <lt_state_Type>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lidar_tracker-msg:num_of_fusedobjects-val is deprecated.  Use lidar_tracker-msg:num_of_fusedobjects instead.")
  (num_of_fusedobjects m))

(cl:ensure-generic-function 'columnscan_up_dist-val :lambda-list '(m))
(cl:defmethod columnscan_up_dist-val ((m <lt_state_Type>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lidar_tracker-msg:columnscan_up_dist-val is deprecated.  Use lidar_tracker-msg:columnscan_up_dist instead.")
  (columnscan_up_dist m))

(cl:ensure-generic-function 'columnscan_down_dist-val :lambda-list '(m))
(cl:defmethod columnscan_down_dist-val ((m <lt_state_Type>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lidar_tracker-msg:columnscan_down_dist-val is deprecated.  Use lidar_tracker-msg:columnscan_down_dist instead.")
  (columnscan_down_dist m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <lt_state_Type>) ostream)
  "Serializes a message object of type '<lt_state_Type>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'timestamp))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'lidars_difftime))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'objects))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'objects))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'trackedcone_indexes))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    ))
   (cl:slot-value msg 'trackedcone_indexes))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'noncone_indexes))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    ))
   (cl:slot-value msg 'noncone_indexes))
  (cl:let* ((signed (cl:slot-value msg 'num_of_fusedobjects)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'columnscan_up_dist))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'columnscan_down_dist))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <lt_state_Type>) istream)
  "Deserializes a message object of type '<lt_state_Type>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'timestamp) (roslisp-utils:decode-double-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'lidars_difftime) (roslisp-utils:decode-double-float-bits bits)))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'objects) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'objects)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'lidar_tracker-msg:lt_object_Type))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'trackedcone_indexes) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'trackedcone_indexes)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'noncone_indexes) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'noncone_indexes)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616)))))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'num_of_fusedobjects) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  (cl:setf (cl:slot-value msg 'columnscan_up_dist) (cl:make-array 8))
  (cl:let ((vals (cl:slot-value msg 'columnscan_up_dist)))
    (cl:dotimes (i 8)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'columnscan_down_dist) (cl:make-array 8))
  (cl:let ((vals (cl:slot-value msg 'columnscan_down_dist)))
    (cl:dotimes (i 8)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<lt_state_Type>)))
  "Returns string type for a message object of type '<lt_state_Type>"
  "lidar_tracker/lt_state_Type")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'lt_state_Type)))
  "Returns string type for a message object of type 'lt_state_Type"
  "lidar_tracker/lt_state_Type")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<lt_state_Type>)))
  "Returns md5sum for a message object of type '<lt_state_Type>"
  "e1e182e21c664b2dc04f11764f16b6e9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'lt_state_Type)))
  "Returns md5sum for a message object of type 'lt_state_Type"
  "e1e182e21c664b2dc04f11764f16b6e9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<lt_state_Type>)))
  "Returns full string definition for message of type '<lt_state_Type>"
  (cl:format cl:nil "# Timestamp [s]~%float64 timestamp~%~%# DiffTime [s]~%float64 lidars_difftime~%~%# Detected Objects~%lidar_tracker/lt_object_Type[] objects~%int64[] trackedcone_indexes ~%int64[] noncone_indexes ~%~%# Detected Objects Stat~%int64 num_of_fusedobjects~%~%# Detected dist(X) for 8 column(Y) scanners~%float64[8] columnscan_up_dist  ~%float64[8] columnscan_down_dist  ~%~%================================================================================~%MSG: lidar_tracker/lt_object_Type~%# Object ID~%int64 ID~%float64 IDTimestamp~%~%# Interval [s]~%float64 UpdateInterval~%~%# Matching ratio~%float64 RatioM~%~%# Object feature points~%lidar_tracker/lt_datapoint_Type MinPoint~%lidar_tracker/lt_datapoint_Type IncEdge~%lidar_tracker/lt_datapoint_Type DecEdge~%lidar_tracker/lt_datapoint_Type CenterPoint~%lidar_tracker/lt_datapoint_Type StableRefPoint~%~%# Object size [m]~%float64 Size~%~%# Object is cone~%bool Is_Cone~%# Object is tracked~%bool Is_Tracked~%~%# Estimated Vel Acc~%lidar_tracker/lt_datapoint_Type Est_Vel~%lidar_tracker/lt_datapoint_Type Est_Acc~%~%# Lidar data fused object~%bool Is_Fused~%~%# Estimated incline angle [rad]~%lidar_tracker/lt_datapoint_Type Incline~%# Estimated rotated angle [rad]~%float64 Rotate~%~%~%================================================================================~%MSG: lidar_tracker/lt_datapoint_Type~%# XY coordinate [m]~%float64  Dist~%float64  Angle~%float64  x~%float64  y~%# RSSI [0~~255]~%float64  intensity~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'lt_state_Type)))
  "Returns full string definition for message of type 'lt_state_Type"
  (cl:format cl:nil "# Timestamp [s]~%float64 timestamp~%~%# DiffTime [s]~%float64 lidars_difftime~%~%# Detected Objects~%lidar_tracker/lt_object_Type[] objects~%int64[] trackedcone_indexes ~%int64[] noncone_indexes ~%~%# Detected Objects Stat~%int64 num_of_fusedobjects~%~%# Detected dist(X) for 8 column(Y) scanners~%float64[8] columnscan_up_dist  ~%float64[8] columnscan_down_dist  ~%~%================================================================================~%MSG: lidar_tracker/lt_object_Type~%# Object ID~%int64 ID~%float64 IDTimestamp~%~%# Interval [s]~%float64 UpdateInterval~%~%# Matching ratio~%float64 RatioM~%~%# Object feature points~%lidar_tracker/lt_datapoint_Type MinPoint~%lidar_tracker/lt_datapoint_Type IncEdge~%lidar_tracker/lt_datapoint_Type DecEdge~%lidar_tracker/lt_datapoint_Type CenterPoint~%lidar_tracker/lt_datapoint_Type StableRefPoint~%~%# Object size [m]~%float64 Size~%~%# Object is cone~%bool Is_Cone~%# Object is tracked~%bool Is_Tracked~%~%# Estimated Vel Acc~%lidar_tracker/lt_datapoint_Type Est_Vel~%lidar_tracker/lt_datapoint_Type Est_Acc~%~%# Lidar data fused object~%bool Is_Fused~%~%# Estimated incline angle [rad]~%lidar_tracker/lt_datapoint_Type Incline~%# Estimated rotated angle [rad]~%float64 Rotate~%~%~%================================================================================~%MSG: lidar_tracker/lt_datapoint_Type~%# XY coordinate [m]~%float64  Dist~%float64  Angle~%float64  x~%float64  y~%# RSSI [0~~255]~%float64  intensity~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <lt_state_Type>))
  (cl:+ 0
     8
     8
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'objects) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'trackedcone_indexes) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'noncone_indexes) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     8
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'columnscan_up_dist) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'columnscan_down_dist) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <lt_state_Type>))
  "Converts a ROS message object to a list"
  (cl:list 'lt_state_Type
    (cl:cons ':timestamp (timestamp msg))
    (cl:cons ':lidars_difftime (lidars_difftime msg))
    (cl:cons ':objects (objects msg))
    (cl:cons ':trackedcone_indexes (trackedcone_indexes msg))
    (cl:cons ':noncone_indexes (noncone_indexes msg))
    (cl:cons ':num_of_fusedobjects (num_of_fusedobjects msg))
    (cl:cons ':columnscan_up_dist (columnscan_up_dist msg))
    (cl:cons ':columnscan_down_dist (columnscan_down_dist msg))
))
