(cl:defpackage lantern_rack-srv
  (:use )
  (:export
   "LR_SET_DOUBLE_ARGS"
   "<LR_SET_DOUBLE_ARGS-REQUEST>"
   "LR_SET_DOUBLE_ARGS-REQUEST"
   "<LR_SET_DOUBLE_ARGS-RESPONSE>"
   "LR_SET_DOUBLE_ARGS-RESPONSE"
   "LR_SET_MODE_ARGS"
   "<LR_SET_MODE_ARGS-REQUEST>"
   "LR_SET_MODE_ARGS-REQUEST"
   "<LR_SET_MODE_ARGS-RESPONSE>"
   "LR_SET_MODE_ARGS-RESPONSE"
  ))

