// Generated by gencpp from file system_io/sio_set_value_ArgsResponse.msg
// DO NOT EDIT!


#ifndef SYSTEM_IO_MESSAGE_SIO_SET_VALUE_ARGSRESPONSE_H
#define SYSTEM_IO_MESSAGE_SIO_SET_VALUE_ARGSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace system_io
{
template <class ContainerAllocator>
struct sio_set_value_ArgsResponse_
{
  typedef sio_set_value_ArgsResponse_<ContainerAllocator> Type;

  sio_set_value_ArgsResponse_()
    : response(0)  {
    }
  sio_set_value_ArgsResponse_(const ContainerAllocator& _alloc)
    : response(0)  {
  (void)_alloc;
    }



   typedef int64_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sio_set_value_ArgsResponse_

typedef ::system_io::sio_set_value_ArgsResponse_<std::allocator<void> > sio_set_value_ArgsResponse;

typedef boost::shared_ptr< ::system_io::sio_set_value_ArgsResponse > sio_set_value_ArgsResponsePtr;
typedef boost::shared_ptr< ::system_io::sio_set_value_ArgsResponse const> sio_set_value_ArgsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator1> & lhs, const ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator1> & lhs, const ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace system_io

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bf37bc717f68787645077428bea3751";
  }

  static const char* value(const ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bf37bc717f68787ULL;
  static const uint64_t static_value2 = 0x645077428bea3751ULL;
};

template<class ContainerAllocator>
struct DataType< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_io/sio_set_value_ArgsResponse";
  }

  static const char* value(const ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 response\n"
"\n"
"\n"
;
  }

  static const char* value(const ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sio_set_value_ArgsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_io::sio_set_value_ArgsResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<int64_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_IO_MESSAGE_SIO_SET_VALUE_ARGSRESPONSE_H
