// Generated by gencpp from file system_io/sio_set_value_ArgsRequest.msg
// DO NOT EDIT!


#ifndef SYSTEM_IO_MESSAGE_SIO_SET_VALUE_ARGSREQUEST_H
#define SYSTEM_IO_MESSAGE_SIO_SET_VALUE_ARGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace system_io
{
template <class ContainerAllocator>
struct sio_set_value_ArgsRequest_
{
  typedef sio_set_value_ArgsRequest_<ContainerAllocator> Type;

  sio_set_value_ArgsRequest_()
    : mask(0)
    , value(0)  {
    }
  sio_set_value_ArgsRequest_(const ContainerAllocator& _alloc)
    : mask(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef int64_t _mask_type;
  _mask_type mask;

   typedef int64_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sio_set_value_ArgsRequest_

typedef ::system_io::sio_set_value_ArgsRequest_<std::allocator<void> > sio_set_value_ArgsRequest;

typedef boost::shared_ptr< ::system_io::sio_set_value_ArgsRequest > sio_set_value_ArgsRequestPtr;
typedef boost::shared_ptr< ::system_io::sio_set_value_ArgsRequest const> sio_set_value_ArgsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator1> & lhs, const ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mask == rhs.mask &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator1> & lhs, const ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace system_io

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efe4a3f733ee9d12e6a99b5b731d228d";
  }

  static const char* value(const ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefe4a3f733ee9d12ULL;
  static const uint64_t static_value2 = 0xe6a99b5b731d228dULL;
};

template<class ContainerAllocator>
struct DataType< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_io/sio_set_value_ArgsRequest";
  }

  static const char* value(const ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 mask\n"
"int64 value\n"
"\n"
;
  }

  static const char* value(const ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mask);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sio_set_value_ArgsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_io::sio_set_value_ArgsRequest_<ContainerAllocator>& v)
  {
    s << indent << "mask: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mask);
    s << indent << "value: ";
    Printer<int64_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_IO_MESSAGE_SIO_SET_VALUE_ARGSREQUEST_H
