(cl:defpackage system_io-srv
  (:use )
  (:export
   "SIO_SET_BOOL_ARGS"
   "<SIO_SET_BOOL_ARGS-REQUEST>"
   "SIO_SET_BOOL_ARGS-REQUEST"
   "<SIO_SET_BOOL_ARGS-RESPONSE>"
   "SIO_SET_BOOL_ARGS-RESPONSE"
   "SIO_SET_DOUBLE_ARGS"
   "<SIO_SET_DOUBLE_ARGS-REQUEST>"
   "SIO_SET_DOUBLE_ARGS-REQUEST"
   "<SIO_SET_DOUBLE_ARGS-RESPONSE>"
   "SIO_SET_DOUBLE_ARGS-RESPONSE"
   "SIO_SET_VALUE_ARGS"
   "<SIO_SET_VALUE_ARGS-REQUEST>"
   "SIO_SET_VALUE_ARGS-REQUEST"
   "<SIO_SET_VALUE_ARGS-RESPONSE>"
   "SIO_SET_VALUE_ARGS-RESPONSE"
  ))

