set(_CATKIN_CURRENT_PACKAGE "system_io")
set(system_io_VERSION "0.0.0")
set(system_io_MAINTAINER "ivanyip <ivanyip@hkpc.org>")
set(system_io_PACKAGE_FORMAT "2")
set(system_io_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(system_io_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(system_io_BUILDTOOL_DEPENDS "catkin")
set(system_io_BUILDTOOL_EXPORT_DEPENDS )
set(system_io_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(system_io_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(system_io_TEST_DEPENDS )
set(system_io_DOC_DEPENDS )
set(system_io_URL_WEBSITE "")
set(system_io_URL_BUGTRACKER "")
set(system_io_URL_REPOSITORY "")
set(system_io_DEPRECATED "")