(cl:defpackage cone_sensor-srv
  (:use )
  (:export
   "CS_SET_BOOL_ARGS"
   "<CS_SET_BOOL_ARGS-REQUEST>"
   "CS_SET_BOOL_ARGS-REQUEST"
   "<CS_SET_BOOL_ARGS-RESPONSE>"
   "CS_SET_BOOL_ARGS-RESPONSE"
   "CS_SET_DOUBLE_ARGS"
   "<CS_SET_DOUBLE_ARGS-REQUEST>"
   "CS_SET_DOUBLE_ARGS-REQUEST"
   "<CS_SET_DOUBLE_ARGS-RESPONSE>"
   "CS_SET_DOUBLE_ARGS-RESPONSE"
  ))

