(cl:in-package kuka_robot-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          POS_SETPT-VAL
          POS_SETPT
          AXIS_SETPT-VAL
          AXIS_SETPT
          POS_FB-VAL
          POS_FB
          AXIS_FB-VAL
          AXIS_FB
          DIST_NEXT-VAL
          DIST_NEXT
          VEL_ACT-VAL
          VEL_ACT
          VEL_AXIS_ACT-VAL
          VEL_AXIS_ACT
          CURR_ACT-VAL
          CURR_ACT
          MOT_TEMP-VAL
          MOT_TEMP
          BRAKE_SIG-VAL
          BRAKE_SIG
          COM_ACTION-VAL
          COM_ACTION
          COM_MOTSTOP-VAL
          COM_MOTSTOP
          COM_LAST_MOT_TIME-VAL
          COM_LAST_MOT_TIME
          COM_DI_PORT_VALUE-VAL
          COM_DI_PORT_VALUE
          COM_DO_PORT_VALUE-VAL
          COM_DO_PORT_VALUE
          COM_ERROR_NO-VAL
          COM_ERROR_NO
          COM_ALARM_NORMAL-VAL
          COM_ALARM_NORMAL
          COM_MOVE_ENABLE-VAL
          COM_MOVE_ENABLE
          COM_AUTEXT_START-VAL
          COM_AUTEXT_START
          MODE_OP-VAL
          MODE_OP
          OV_PRO-VAL
          OV_PRO
          POWER_FAIL-VAL
          POWER_FAIL
          SAFETY_SW-VAL
          SAFETY_SW
          ERR-VAL
          ERR
))