(cl:defpackage vision_system-srv
  (:use )
  (:export
   "VS_CHECK_POSITION_HAS_CONE_ARGS"
   "<VS_CHECK_POSITION_HAS_CONE_ARGS-REQUEST>"
   "VS_CHECK_POSITION_HAS_CONE_ARGS-REQUEST"
   "<VS_CHECK_POSITION_HAS_CONE_ARGS-RESPONSE>"
   "VS_CHECK_POSITION_HAS_CONE_ARGS-RESPONSE"
   "VS_GET_WHITE_MARKING_POSITION_ARGS"
   "<VS_GET_WHITE_MARKING_POSITION_ARGS-REQUEST>"
   "VS_GET_WHITE_MARKING_POSITION_ARGS-REQUEST"
   "<VS_GET_WHITE_MARKING_POSITION_ARGS-RESPONSE>"
   "VS_GET_WHITE_MARKING_POSITION_ARGS-RESPONSE"
   "VS_SEND_CALI_DATA_ARGS"
   "<VS_SEND_CALI_DATA_ARGS-REQUEST>"
   "VS_SEND_CALI_DATA_ARGS-REQUEST"
   "<VS_SEND_CALI_DATA_ARGS-RESPONSE>"
   "VS_SEND_CALI_DATA_ARGS-RESPONSE"
  ))

