// Generated by gencpp from file power_system/ps_set_double_Args.msg
// DO NOT EDIT!


#ifndef POWER_SYSTEM_MESSAGE_PS_SET_DOUBLE_ARGS_H
#define POWER_SYSTEM_MESSAGE_PS_SET_DOUBLE_ARGS_H

#include <ros/service_traits.h>


#include <power_system/ps_set_double_ArgsRequest.h>
#include <power_system/ps_set_double_ArgsResponse.h>


namespace power_system
{

struct ps_set_double_Args
{

typedef ps_set_double_ArgsRequest Request;
typedef ps_set_double_ArgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ps_set_double_Args
} // namespace power_system


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::power_system::ps_set_double_Args > {
  static const char* value()
  {
    return "1320d4a929ea6ef2a246c2b190a9f356";
  }

  static const char* value(const ::power_system::ps_set_double_Args&) { return value(); }
};

template<>
struct DataType< ::power_system::ps_set_double_Args > {
  static const char* value()
  {
    return "power_system/ps_set_double_Args";
  }

  static const char* value(const ::power_system::ps_set_double_Args&) { return value(); }
};


// service_traits::MD5Sum< ::power_system::ps_set_double_ArgsRequest> should match
// service_traits::MD5Sum< ::power_system::ps_set_double_Args >
template<>
struct MD5Sum< ::power_system::ps_set_double_ArgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::power_system::ps_set_double_Args >::value();
  }
  static const char* value(const ::power_system::ps_set_double_ArgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::power_system::ps_set_double_ArgsRequest> should match
// service_traits::DataType< ::power_system::ps_set_double_Args >
template<>
struct DataType< ::power_system::ps_set_double_ArgsRequest>
{
  static const char* value()
  {
    return DataType< ::power_system::ps_set_double_Args >::value();
  }
  static const char* value(const ::power_system::ps_set_double_ArgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::power_system::ps_set_double_ArgsResponse> should match
// service_traits::MD5Sum< ::power_system::ps_set_double_Args >
template<>
struct MD5Sum< ::power_system::ps_set_double_ArgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::power_system::ps_set_double_Args >::value();
  }
  static const char* value(const ::power_system::ps_set_double_ArgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::power_system::ps_set_double_ArgsResponse> should match
// service_traits::DataType< ::power_system::ps_set_double_Args >
template<>
struct DataType< ::power_system::ps_set_double_ArgsResponse>
{
  static const char* value()
  {
    return DataType< ::power_system::ps_set_double_Args >::value();
  }
  static const char* value(const ::power_system::ps_set_double_ArgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POWER_SYSTEM_MESSAGE_PS_SET_DOUBLE_ARGS_H
