set(_CATKIN_CURRENT_PACKAGE "lantern_rack")
set(lantern_rack_VERSION "0.0.0")
set(lantern_rack_MAINTAINER "ivanyip <ivanyip@hkpc.org>")
set(lantern_rack_PACKAGE_FORMAT "2")
set(lantern_rack_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(lantern_rack_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(lantern_rack_BUILDTOOL_DEPENDS "catkin")
set(lantern_rack_BUILDTOOL_EXPORT_DEPENDS )
set(lantern_rack_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(lantern_rack_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(lantern_rack_TEST_DEPENDS )
set(lantern_rack_DOC_DEPENDS )
set(lantern_rack_URL_WEBSITE "")
set(lantern_rack_URL_BUGTRACKER "")
set(lantern_rack_URL_REPOSITORY "")
set(lantern_rack_DEPRECATED "")