// Generated by gencpp from file kuka_robot/kr_batch_mv_run_ArgsRequest.msg
// DO NOT EDIT!


#ifndef KUKA_ROBOT_MESSAGE_KR_BATCH_MV_RUN_ARGSREQUEST_H
#define KUKA_ROBOT_MESSAGE_KR_BATCH_MV_RUN_ARGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuka_robot
{
template <class ContainerAllocator>
struct kr_batch_mv_run_ArgsRequest_
{
  typedef kr_batch_mv_run_ArgsRequest_<ContainerAllocator> Type;

  kr_batch_mv_run_ArgsRequest_()
    : start_block(0)
    , end_block(0)  {
    }
  kr_batch_mv_run_ArgsRequest_(const ContainerAllocator& _alloc)
    : start_block(0)
    , end_block(0)  {
  (void)_alloc;
    }



   typedef int64_t _start_block_type;
  _start_block_type start_block;

   typedef int64_t _end_block_type;
  _end_block_type end_block;





  typedef boost::shared_ptr< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct kr_batch_mv_run_ArgsRequest_

typedef ::kuka_robot::kr_batch_mv_run_ArgsRequest_<std::allocator<void> > kr_batch_mv_run_ArgsRequest;

typedef boost::shared_ptr< ::kuka_robot::kr_batch_mv_run_ArgsRequest > kr_batch_mv_run_ArgsRequestPtr;
typedef boost::shared_ptr< ::kuka_robot::kr_batch_mv_run_ArgsRequest const> kr_batch_mv_run_ArgsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start_block == rhs.start_block &&
    lhs.end_block == rhs.end_block;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuka_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6d269f526c3fea92a58d97e181df9e8";
  }

  static const char* value(const ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6d269f526c3fea9ULL;
  static const uint64_t static_value2 = 0x2a58d97e181df9e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_robot/kr_batch_mv_run_ArgsRequest";
  }

  static const char* value(const ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 start_block\n"
"\n"
"int64 end_block\n"
;
  }

  static const char* value(const ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_block);
      stream.next(m.end_block);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kr_batch_mv_run_ArgsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_robot::kr_batch_mv_run_ArgsRequest_<ContainerAllocator>& v)
  {
    s << indent << "start_block: ";
    Printer<int64_t>::stream(s, indent + "  ", v.start_block);
    s << indent << "end_block: ";
    Printer<int64_t>::stream(s, indent + "  ", v.end_block);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_ROBOT_MESSAGE_KR_BATCH_MV_RUN_ARGSREQUEST_H
