// Generated by gencpp from file kuka_robot/kr_cov_joint_pose_ArgsResponse.msg
// DO NOT EDIT!


#ifndef KUKA_ROBOT_MESSAGE_KR_COV_JOINT_POSE_ARGSRESPONSE_H
#define KUKA_ROBOT_MESSAGE_KR_COV_JOINT_POSE_ARGSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kuka_robot/kr_pose_Type.h>

namespace kuka_robot
{
template <class ContainerAllocator>
struct kr_cov_joint_pose_ArgsResponse_
{
  typedef kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> Type;

  kr_cov_joint_pose_ArgsResponse_()
    : response(0)
    , pose()  {
    }
  kr_cov_joint_pose_ArgsResponse_(const ContainerAllocator& _alloc)
    : response(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _response_type;
  _response_type response;

   typedef  ::kuka_robot::kr_pose_Type_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct kr_cov_joint_pose_ArgsResponse_

typedef ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<std::allocator<void> > kr_cov_joint_pose_ArgsResponse;

typedef boost::shared_ptr< ::kuka_robot::kr_cov_joint_pose_ArgsResponse > kr_cov_joint_pose_ArgsResponsePtr;
typedef boost::shared_ptr< ::kuka_robot::kr_cov_joint_pose_ArgsResponse const> kr_cov_joint_pose_ArgsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuka_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd36ce0f79aa02f97968c7902bb4971d";
  }

  static const char* value(const ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd36ce0f79aa02f9ULL;
  static const uint64_t static_value2 = 0x7968c7902bb4971dULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_robot/kr_cov_joint_pose_ArgsResponse";
  }

  static const char* value(const ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 response\n"
"\n"
"kr_pose_Type pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: kuka_robot/kr_pose_Type\n"
"# XYZ coordinate [mm]\n"
"float64 X\n"
"float64 Y\n"
"float64 Z\n"
"# ABC orientation [mm]\n"
"float64 A\n"
"float64 B\n"
"float64 C\n"
"# Status and Turn [unit]\n"
"float64 S\n"
"float64 T\n"
;
  }

  static const char* value(const ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kr_cov_joint_pose_ArgsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_robot::kr_cov_joint_pose_ArgsResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<int64_t>::stream(s, indent + "  ", v.response);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::kuka_robot::kr_pose_Type_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_ROBOT_MESSAGE_KR_COV_JOINT_POSE_ARGSRESPONSE_H
