// Generated by gencpp from file kuka_robot/kr_dummy_ArgsRequest.msg
// DO NOT EDIT!


#ifndef KUKA_ROBOT_MESSAGE_KR_DUMMY_ARGSREQUEST_H
#define KUKA_ROBOT_MESSAGE_KR_DUMMY_ARGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuka_robot
{
template <class ContainerAllocator>
struct kr_dummy_ArgsRequest_
{
  typedef kr_dummy_ArgsRequest_<ContainerAllocator> Type;

  kr_dummy_ArgsRequest_()
    : dummy(0)  {
    }
  kr_dummy_ArgsRequest_(const ContainerAllocator& _alloc)
    : dummy(0)  {
  (void)_alloc;
    }



   typedef int64_t _dummy_type;
  _dummy_type dummy;





  typedef boost::shared_ptr< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct kr_dummy_ArgsRequest_

typedef ::kuka_robot::kr_dummy_ArgsRequest_<std::allocator<void> > kr_dummy_ArgsRequest;

typedef boost::shared_ptr< ::kuka_robot::kr_dummy_ArgsRequest > kr_dummy_ArgsRequestPtr;
typedef boost::shared_ptr< ::kuka_robot::kr_dummy_ArgsRequest const> kr_dummy_ArgsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.dummy == rhs.dummy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuka_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a62b28fdf54afb8d2ce8b90d7336086";
  }

  static const char* value(const ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a62b28fdf54afb8ULL;
  static const uint64_t static_value2 = 0xd2ce8b90d7336086ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_robot/kr_dummy_ArgsRequest";
  }

  static const char* value(const ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 dummy\n"
;
  }

  static const char* value(const ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dummy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kr_dummy_ArgsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_robot::kr_dummy_ArgsRequest_<ContainerAllocator>& v)
  {
    s << indent << "dummy: ";
    Printer<int64_t>::stream(s, indent + "  ", v.dummy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_ROBOT_MESSAGE_KR_DUMMY_ARGSREQUEST_H
