// Generated by gencpp from file kuka_robot/kr_dummy_Args.msg
// DO NOT EDIT!


#ifndef KUKA_ROBOT_MESSAGE_KR_DUMMY_ARGS_H
#define KUKA_ROBOT_MESSAGE_KR_DUMMY_ARGS_H

#include <ros/service_traits.h>


#include <kuka_robot/kr_dummy_ArgsRequest.h>
#include <kuka_robot/kr_dummy_ArgsResponse.h>


namespace kuka_robot
{

struct kr_dummy_Args
{

typedef kr_dummy_ArgsRequest Request;
typedef kr_dummy_ArgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct kr_dummy_Args
} // namespace kuka_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuka_robot::kr_dummy_Args > {
  static const char* value()
  {
    return "33736ff8569e3bd56de924f3e76e8121";
  }

  static const char* value(const ::kuka_robot::kr_dummy_Args&) { return value(); }
};

template<>
struct DataType< ::kuka_robot::kr_dummy_Args > {
  static const char* value()
  {
    return "kuka_robot/kr_dummy_Args";
  }

  static const char* value(const ::kuka_robot::kr_dummy_Args&) { return value(); }
};


// service_traits::MD5Sum< ::kuka_robot::kr_dummy_ArgsRequest> should match
// service_traits::MD5Sum< ::kuka_robot::kr_dummy_Args >
template<>
struct MD5Sum< ::kuka_robot::kr_dummy_ArgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_robot::kr_dummy_Args >::value();
  }
  static const char* value(const ::kuka_robot::kr_dummy_ArgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_robot::kr_dummy_ArgsRequest> should match
// service_traits::DataType< ::kuka_robot::kr_dummy_Args >
template<>
struct DataType< ::kuka_robot::kr_dummy_ArgsRequest>
{
  static const char* value()
  {
    return DataType< ::kuka_robot::kr_dummy_Args >::value();
  }
  static const char* value(const ::kuka_robot::kr_dummy_ArgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuka_robot::kr_dummy_ArgsResponse> should match
// service_traits::MD5Sum< ::kuka_robot::kr_dummy_Args >
template<>
struct MD5Sum< ::kuka_robot::kr_dummy_ArgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_robot::kr_dummy_Args >::value();
  }
  static const char* value(const ::kuka_robot::kr_dummy_ArgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_robot::kr_dummy_ArgsResponse> should match
// service_traits::DataType< ::kuka_robot::kr_dummy_Args >
template<>
struct DataType< ::kuka_robot::kr_dummy_ArgsResponse>
{
  static const char* value()
  {
    return DataType< ::kuka_robot::kr_dummy_Args >::value();
  }
  static const char* value(const ::kuka_robot::kr_dummy_ArgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUKA_ROBOT_MESSAGE_KR_DUMMY_ARGS_H
