// Generated by gencpp from file kuka_robot/kr_mv_bypose_ArgsResponse.msg
// DO NOT EDIT!


#ifndef KUKA_ROBOT_MESSAGE_KR_MV_BYPOSE_ARGSRESPONSE_H
#define KUKA_ROBOT_MESSAGE_KR_MV_BYPOSE_ARGSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuka_robot
{
template <class ContainerAllocator>
struct kr_mv_bypose_ArgsResponse_
{
  typedef kr_mv_bypose_ArgsResponse_<ContainerAllocator> Type;

  kr_mv_bypose_ArgsResponse_()
    : response(0)  {
    }
  kr_mv_bypose_ArgsResponse_(const ContainerAllocator& _alloc)
    : response(0)  {
  (void)_alloc;
    }



   typedef int64_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct kr_mv_bypose_ArgsResponse_

typedef ::kuka_robot::kr_mv_bypose_ArgsResponse_<std::allocator<void> > kr_mv_bypose_ArgsResponse;

typedef boost::shared_ptr< ::kuka_robot::kr_mv_bypose_ArgsResponse > kr_mv_bypose_ArgsResponsePtr;
typedef boost::shared_ptr< ::kuka_robot::kr_mv_bypose_ArgsResponse const> kr_mv_bypose_ArgsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuka_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bf37bc717f68787645077428bea3751";
  }

  static const char* value(const ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bf37bc717f68787ULL;
  static const uint64_t static_value2 = 0x645077428bea3751ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_robot/kr_mv_bypose_ArgsResponse";
  }

  static const char* value(const ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 response\n"
"\n"
;
  }

  static const char* value(const ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kr_mv_bypose_ArgsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_robot::kr_mv_bypose_ArgsResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<int64_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_ROBOT_MESSAGE_KR_MV_BYPOSE_ARGSRESPONSE_H
