// Generated by gencpp from file kuka_robot/kr_mv_bypose_Args.msg
// DO NOT EDIT!


#ifndef KUKA_ROBOT_MESSAGE_KR_MV_BYPOSE_ARGS_H
#define KUKA_ROBOT_MESSAGE_KR_MV_BYPOSE_ARGS_H

#include <ros/service_traits.h>


#include <kuka_robot/kr_mv_bypose_ArgsRequest.h>
#include <kuka_robot/kr_mv_bypose_ArgsResponse.h>


namespace kuka_robot
{

struct kr_mv_bypose_Args
{

typedef kr_mv_bypose_ArgsRequest Request;
typedef kr_mv_bypose_ArgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct kr_mv_bypose_Args
} // namespace kuka_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuka_robot::kr_mv_bypose_Args > {
  static const char* value()
  {
    return "8c20ec7ca823ece0c21366ed77a91e58";
  }

  static const char* value(const ::kuka_robot::kr_mv_bypose_Args&) { return value(); }
};

template<>
struct DataType< ::kuka_robot::kr_mv_bypose_Args > {
  static const char* value()
  {
    return "kuka_robot/kr_mv_bypose_Args";
  }

  static const char* value(const ::kuka_robot::kr_mv_bypose_Args&) { return value(); }
};


// service_traits::MD5Sum< ::kuka_robot::kr_mv_bypose_ArgsRequest> should match
// service_traits::MD5Sum< ::kuka_robot::kr_mv_bypose_Args >
template<>
struct MD5Sum< ::kuka_robot::kr_mv_bypose_ArgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_robot::kr_mv_bypose_Args >::value();
  }
  static const char* value(const ::kuka_robot::kr_mv_bypose_ArgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_robot::kr_mv_bypose_ArgsRequest> should match
// service_traits::DataType< ::kuka_robot::kr_mv_bypose_Args >
template<>
struct DataType< ::kuka_robot::kr_mv_bypose_ArgsRequest>
{
  static const char* value()
  {
    return DataType< ::kuka_robot::kr_mv_bypose_Args >::value();
  }
  static const char* value(const ::kuka_robot::kr_mv_bypose_ArgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuka_robot::kr_mv_bypose_ArgsResponse> should match
// service_traits::MD5Sum< ::kuka_robot::kr_mv_bypose_Args >
template<>
struct MD5Sum< ::kuka_robot::kr_mv_bypose_ArgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_robot::kr_mv_bypose_Args >::value();
  }
  static const char* value(const ::kuka_robot::kr_mv_bypose_ArgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_robot::kr_mv_bypose_ArgsResponse> should match
// service_traits::DataType< ::kuka_robot::kr_mv_bypose_Args >
template<>
struct DataType< ::kuka_robot::kr_mv_bypose_ArgsResponse>
{
  static const char* value()
  {
    return DataType< ::kuka_robot::kr_mv_bypose_Args >::value();
  }
  static const char* value(const ::kuka_robot::kr_mv_bypose_ArgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUKA_ROBOT_MESSAGE_KR_MV_BYPOSE_ARGS_H
