// Generated by gencpp from file kuka_robot/kr_setdo_ArgsRequest.msg
// DO NOT EDIT!


#ifndef KUKA_ROBOT_MESSAGE_KR_SETDO_ARGSREQUEST_H
#define KUKA_ROBOT_MESSAGE_KR_SETDO_ARGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuka_robot
{
template <class ContainerAllocator>
struct kr_setdo_ArgsRequest_
{
  typedef kr_setdo_ArgsRequest_<ContainerAllocator> Type;

  kr_setdo_ArgsRequest_()
    : mask(0)
    , value(0)
    , settle_sec(0.0)  {
    }
  kr_setdo_ArgsRequest_(const ContainerAllocator& _alloc)
    : mask(0)
    , value(0)
    , settle_sec(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _mask_type;
  _mask_type mask;

   typedef int64_t _value_type;
  _value_type value;

   typedef double _settle_sec_type;
  _settle_sec_type settle_sec;





  typedef boost::shared_ptr< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct kr_setdo_ArgsRequest_

typedef ::kuka_robot::kr_setdo_ArgsRequest_<std::allocator<void> > kr_setdo_ArgsRequest;

typedef boost::shared_ptr< ::kuka_robot::kr_setdo_ArgsRequest > kr_setdo_ArgsRequestPtr;
typedef boost::shared_ptr< ::kuka_robot::kr_setdo_ArgsRequest const> kr_setdo_ArgsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mask == rhs.mask &&
    lhs.value == rhs.value &&
    lhs.settle_sec == rhs.settle_sec;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuka_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3ddd3317421f075ba386d86f343289a";
  }

  static const char* value(const ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3ddd3317421f075ULL;
  static const uint64_t static_value2 = 0xba386d86f343289aULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_robot/kr_setdo_ArgsRequest";
  }

  static const char* value(const ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 mask\n"
"\n"
"int64 value\n"
"\n"
"float64 settle_sec\n"
;
  }

  static const char* value(const ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mask);
      stream.next(m.value);
      stream.next(m.settle_sec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kr_setdo_ArgsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_robot::kr_setdo_ArgsRequest_<ContainerAllocator>& v)
  {
    s << indent << "mask: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mask);
    s << indent << "value: ";
    Printer<int64_t>::stream(s, indent + "  ", v.value);
    s << indent << "settle_sec: ";
    Printer<double>::stream(s, indent + "  ", v.settle_sec);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_ROBOT_MESSAGE_KR_SETDO_ARGSREQUEST_H
