// Generated by gencpp from file kuka_robot/kr_set_real_ArgsRequest.msg
// DO NOT EDIT!


#ifndef KUKA_ROBOT_MESSAGE_KR_SET_REAL_ARGSREQUEST_H
#define KUKA_ROBOT_MESSAGE_KR_SET_REAL_ARGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuka_robot
{
template <class ContainerAllocator>
struct kr_set_real_ArgsRequest_
{
  typedef kr_set_real_ArgsRequest_<ContainerAllocator> Type;

  kr_set_real_ArgsRequest_()
    : number(0.0)  {
    }
  kr_set_real_ArgsRequest_(const ContainerAllocator& _alloc)
    : number(0.0)  {
  (void)_alloc;
    }



   typedef double _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct kr_set_real_ArgsRequest_

typedef ::kuka_robot::kr_set_real_ArgsRequest_<std::allocator<void> > kr_set_real_ArgsRequest;

typedef boost::shared_ptr< ::kuka_robot::kr_set_real_ArgsRequest > kr_set_real_ArgsRequestPtr;
typedef boost::shared_ptr< ::kuka_robot::kr_set_real_ArgsRequest const> kr_set_real_ArgsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuka_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4dcebbc33e65171f948c63edad2d5dae";
  }

  static const char* value(const ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4dcebbc33e65171fULL;
  static const uint64_t static_value2 = 0x948c63edad2d5daeULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_robot/kr_set_real_ArgsRequest";
  }

  static const char* value(const ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 number\n"
;
  }

  static const char* value(const ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kr_set_real_ArgsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_robot::kr_set_real_ArgsRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<double>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_ROBOT_MESSAGE_KR_SET_REAL_ARGSREQUEST_H
