// Generated by gencpp from file kuka_robot/kr_set_accvel_ArgsRequest.msg
// DO NOT EDIT!


#ifndef KUKA_ROBOT_MESSAGE_KR_SET_ACCVEL_ARGSREQUEST_H
#define KUKA_ROBOT_MESSAGE_KR_SET_ACCVEL_ARGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuka_robot
{
template <class ContainerAllocator>
struct kr_set_accvel_ArgsRequest_
{
  typedef kr_set_accvel_ArgsRequest_<ContainerAllocator> Type;

  kr_set_accvel_ArgsRequest_()
    : acc(0.0)
    , acc_swivel(0.0)
    , acc_rot(0.0)
    , vel(0.0)
    , vel_swivel(0.0)
    , vel_rot(0.0)  {
    }
  kr_set_accvel_ArgsRequest_(const ContainerAllocator& _alloc)
    : acc(0.0)
    , acc_swivel(0.0)
    , acc_rot(0.0)
    , vel(0.0)
    , vel_swivel(0.0)
    , vel_rot(0.0)  {
  (void)_alloc;
    }



   typedef double _acc_type;
  _acc_type acc;

   typedef double _acc_swivel_type;
  _acc_swivel_type acc_swivel;

   typedef double _acc_rot_type;
  _acc_rot_type acc_rot;

   typedef double _vel_type;
  _vel_type vel;

   typedef double _vel_swivel_type;
  _vel_swivel_type vel_swivel;

   typedef double _vel_rot_type;
  _vel_rot_type vel_rot;





  typedef boost::shared_ptr< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct kr_set_accvel_ArgsRequest_

typedef ::kuka_robot::kr_set_accvel_ArgsRequest_<std::allocator<void> > kr_set_accvel_ArgsRequest;

typedef boost::shared_ptr< ::kuka_robot::kr_set_accvel_ArgsRequest > kr_set_accvel_ArgsRequestPtr;
typedef boost::shared_ptr< ::kuka_robot::kr_set_accvel_ArgsRequest const> kr_set_accvel_ArgsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.acc == rhs.acc &&
    lhs.acc_swivel == rhs.acc_swivel &&
    lhs.acc_rot == rhs.acc_rot &&
    lhs.vel == rhs.vel &&
    lhs.vel_swivel == rhs.vel_swivel &&
    lhs.vel_rot == rhs.vel_rot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator1> & lhs, const ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuka_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "705361753af8b429ac30c80b343ed051";
  }

  static const char* value(const ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x705361753af8b429ULL;
  static const uint64_t static_value2 = 0xac30c80b343ed051ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_robot/kr_set_accvel_ArgsRequest";
  }

  static const char* value(const ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 acc\n"
"\n"
"float64 acc_swivel\n"
"\n"
"float64 acc_rot\n"
"\n"
"float64 vel\n"
"\n"
"float64 vel_swivel\n"
"\n"
"float64 vel_rot\n"
;
  }

  static const char* value(const ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acc);
      stream.next(m.acc_swivel);
      stream.next(m.acc_rot);
      stream.next(m.vel);
      stream.next(m.vel_swivel);
      stream.next(m.vel_rot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kr_set_accvel_ArgsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_robot::kr_set_accvel_ArgsRequest_<ContainerAllocator>& v)
  {
    s << indent << "acc: ";
    Printer<double>::stream(s, indent + "  ", v.acc);
    s << indent << "acc_swivel: ";
    Printer<double>::stream(s, indent + "  ", v.acc_swivel);
    s << indent << "acc_rot: ";
    Printer<double>::stream(s, indent + "  ", v.acc_rot);
    s << indent << "vel: ";
    Printer<double>::stream(s, indent + "  ", v.vel);
    s << indent << "vel_swivel: ";
    Printer<double>::stream(s, indent + "  ", v.vel_swivel);
    s << indent << "vel_rot: ";
    Printer<double>::stream(s, indent + "  ", v.vel_rot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_ROBOT_MESSAGE_KR_SET_ACCVEL_ARGSREQUEST_H
