// Generated by gencpp from file lantern_rack/lr_set_double_ArgsRequest.msg
// DO NOT EDIT!


#ifndef LANTERN_RACK_MESSAGE_LR_SET_DOUBLE_ARGSREQUEST_H
#define LANTERN_RACK_MESSAGE_LR_SET_DOUBLE_ARGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lantern_rack
{
template <class ContainerAllocator>
struct lr_set_double_ArgsRequest_
{
  typedef lr_set_double_ArgsRequest_<ContainerAllocator> Type;

  lr_set_double_ArgsRequest_()
    : num(0.0)  {
    }
  lr_set_double_ArgsRequest_(const ContainerAllocator& _alloc)
    : num(0.0)  {
  (void)_alloc;
    }



   typedef double _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct lr_set_double_ArgsRequest_

typedef ::lantern_rack::lr_set_double_ArgsRequest_<std::allocator<void> > lr_set_double_ArgsRequest;

typedef boost::shared_ptr< ::lantern_rack::lr_set_double_ArgsRequest > lr_set_double_ArgsRequestPtr;
typedef boost::shared_ptr< ::lantern_rack::lr_set_double_ArgsRequest const> lr_set_double_ArgsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator1> & lhs, const ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator1> & lhs, const ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lantern_rack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f942a3e0cbd340847b2a0e5b31a783fe";
  }

  static const char* value(const ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf942a3e0cbd34084ULL;
  static const uint64_t static_value2 = 0x7b2a0e5b31a783feULL;
};

template<class ContainerAllocator>
struct DataType< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lantern_rack/lr_set_double_ArgsRequest";
  }

  static const char* value(const ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 num\n"
;
  }

  static const char* value(const ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lr_set_double_ArgsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lantern_rack::lr_set_double_ArgsRequest_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<double>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LANTERN_RACK_MESSAGE_LR_SET_DOUBLE_ARGSREQUEST_H
