(cl:defpackage power_system-srv
  (:use )
  (:export
   "PS_SET_BOOL_ARGS"
   "<PS_SET_BOOL_ARGS-REQUEST>"
   "PS_SET_BOOL_ARGS-REQUEST"
   "<PS_SET_BOOL_ARGS-RESPONSE>"
   "PS_SET_BOOL_ARGS-RESPONSE"
   "PS_SET_DOUBLE_ARGS"
   "<PS_SET_DOUBLE_ARGS-REQUEST>"
   "PS_SET_DOUBLE_ARGS-REQUEST"
   "<PS_SET_DOUBLE_ARGS-RESPONSE>"
   "PS_SET_DOUBLE_ARGS-RESPONSE"
  ))

